// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPzOZULjpfGdu4N_eCAvwjPkwSCoeG6g0',
    appId: '1:190226247499:web:598e0ef4858c41b56042ce',
    messagingSenderId: '190226247499',
    projectId: 'icreditmx69',
    authDomain: 'icreditmx69.firebaseapp.com',
    databaseURL: 'https://icreditmx69-default-rtdb.firebaseio.com',
    storageBucket: 'icreditmx69.appspot.com',
    measurementId: 'G-0F57JKVHJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFSPLltx2z3pI4NMvo68eIegqDJQdXEvw',
    appId: '1:190226247499:android:06764f155c2304bf6042ce',
    messagingSenderId: '190226247499',
    projectId: 'icreditmx69',
    databaseURL: 'https://icreditmx69-default-rtdb.firebaseio.com',
    storageBucket: 'icreditmx69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTSgJIiP8RZOxoUb1wjvi4x9k2WiHKsiQ',
    appId: '1:190226247499:ios:ae841a852a10aff96042ce',
    messagingSenderId: '190226247499',
    projectId: 'icreditmx69',
    databaseURL: 'https://icreditmx69-default-rtdb.firebaseio.com',
    storageBucket: 'icreditmx69.appspot.com',
    iosBundleId: 'com.xubenx.icredit',
  );
}
